---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openssh
spec:
  chartRef:
    kind: OCIRepository
    name: openssh
  install:
    remediation:
      retries: -1
  interval: 30m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      openssh:
        containers:
          app:
            command:
              - /usr/sbin/sshd.pam
              - '-Def'
              - /config/ssh_host_keys/sshd_config
              - '-p'
              - '2222'
            image:
              repository: ghcr.io/linuxserver/openssh-server
              tag: latest
            probes:
              liveness: &probe
                custom: true
                enabled: true
                spec: &probeSpec
                  exec:
                    command:
                      - '/usr/bin/fuser'
                      - '2222/tcp'
                  failureThreshold: 3
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 1
              readiness:
                <<: *probe
              startup:
                <<: *probe
                spec:
                  <<: *probeSpec
                  initialDelaySeconds: 15
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 25m
                memory: 25Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
        pod:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
                  weight: 1
          annotations:
            reloader.stakater.com/auto: 'true'
          securityContext:
            fsGroup: 911
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 911
            runAsUser: 911
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
          topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: openssh
              maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
        replicas: 1
        rollingUpdate:
          surge: 1
        strategy: RollingUpdate
    networkpolicies:
      openssh:
        controller: openssh
        enabled: true
        policyTypes:
          - Ingress
        rules:
          ingress:
            # Allow SSH from Gateway
            - from:
                - ipBlock:
                    cidr: 10.0.4.1/32
              ports:
                - port: 2222
                  protocol: TCP
    persistence:
      config:
        globalMounts:
          - path: /config/.ssh/authorized_keys
            subPath: authorized_keys
          #- path: /config/.ssh/known_hosts
          #  subPath: known_hosts
          #- path: /config/ssh_host_keys/ssh_config
          #  subPath: ssh_config
          - path: /config/ssh_host_keys/sshd_config
            subPath: sshd_config
          #- path: /config/ssh_host_keys/ssh_known_hosts
          #  subPath: ssh_known_hosts
          - path: /config/ssh_host_keys/ssh_host_dsa_key
            subPath: ssh_host_dsa_key
          - path: /config/ssh_host_keys/ssh_host_dsa_key.pub
            subPath: ssh_host_dsa_key.pub
          - path: /config/ssh_host_keys/ssh_host_ecdsa_key
            subPath: ssh_host_ecdsa_key
          - path: /config/ssh_host_keys/ssh_host_ecdsa_key.pub
            subPath: ssh_host_ecdsa_key.pub
          - path: /config/ssh_host_keys/ssh_host_ed25519_key
            subPath: ssh_host_ed25519_key
          - path: /config/ssh_host_keys/ssh_host_ed25519_key.pub
            subPath: ssh_host_ed25519_key.pub
          - path: /config/ssh_host_keys/ssh_host_rsa_key
            subPath: ssh_host_rsa_key
          - path: /config/ssh_host_keys/ssh_host_rsa_key.pub
            subPath: ssh_host_rsa_key.pub
        name: openssh
        type: secret
    service:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: openssh.${SECRET_DOMAIN}
          io.cilium/lb-ipam-ips: 10.44.0.6
        controller: openssh
        externalTrafficPolicy: Local
        ports:
          ssh:
            port: 22
            protocol: TCP
            targetPort: 2222
        type: LoadBalancer
