---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin-sync
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: jellyfin-sync
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      jellyfin-sync:
        annotations:
          reloader.stakater.com/auto: "true"
        type: cronjob
        cronjob:
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        containers:
          app:
            image:
              repository: ghcr.io/luigi311/jellyplex-watched
              tag: 8.2.0@sha256:cbd8712389848cb5a2c9a54f712d7aded184cf2233bea4db9d5a890083e2f30e
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            env:
              DEBUG_LEVEL: debug
              DRYRUN: true
              JELLYFIN_BASEURL: http://jellyfin.media.svc.cluster.local:8096
              LOGFILE: /tmp/sync.log
              MARK_FILE: /tmp/mark.log
              PLEX_BASEURL: http://plex.media.svc.cluster.local:32400
              RUN_ONLY_ONCE: true
              TZ: "${TIMEZONE}"
              USER_MAPPING: '{"Wasurerarenai": "michael"}'
              WHITELIST_LIBRARY: Movies,Shows
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          hostUsers: false
          restartPolicy: Never
    persistence:
      tmp:
        type: emptyDir
