---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age19838570kqjm060wxe9lc9pclvum5tzepsgnc6r6h8l8sccartexq7g05rn"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age19838570kqjm060wxe9lc9pclvum5tzepsgnc6r6h8l8sccartexq7g05rn"
stores:
  yaml:
    indent: 2
