---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
      params:
        - name: unifi
          module:
            - ubiquiti_unifi
          target: 10.0.1.1
          auth:
            - public_v2
      path: /snmp
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels:
            - __param_target
          targetLabel: instance
