---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default: task --list

  reboot-node:
    desc: Reboot Talos on a single node [IP=required] [MODE=default]
    cmds:
      - task: down
      - talosctl --nodes {{.IP}} reboot --mode={{.MODE}}
      - talosctl --nodes {{.IP}} health
      - task: up
    vars:
      MODE: '{{.MODE | default "default"}}'
    requires:
      vars: [IP]
    preconditions:
      - talosctl --nodes {{.IP}} get machineconfig
      - talosctl config info
      - test -f {{.TALHELPER_DIR}}/.cluster.env
      - test -f {{.TALHELPER_DIR}}/clusterconfig/talosconfig
      - which talosctl

  shutdown-cluster:
    desc: Shutdown Talos across the whole cluster
    prompt: Shutdown the Talos cluster ... continue?
    cmd: talosctl shutdown --nodes {{.IP_ADDRS}} --force
    vars:
      IP_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(",")'
    preconditions:
      - talosctl --nodes {{.NODES}} get machineconfig
      - talosctl config info
      - test -f {{.TALHELPER_DIR}}/clusterconfig/talosconfig
      - which jq talosctl

  reset-node:
    desc: Reset Talos on a single node [IP=required]
    prompt: Reset Talos node '{{.IP}}' ... continue?
    cmd: talosctl reset --nodes {{.IP}} --graceful=false
    requires:
      vars: [IP]
    preconditions:
      - talosctl --nodes {{.IP}} get machineconfig
      - talosctl config info
      - test -f {{.TALHELPER_DIR}}/clusterconfig/talosconfig
      - which talosctl

  apply-cluster:
    desc: Apply Talos config across the whole cluster [MODE=default]
    cmds:
      - for: { var: IP_ADDRS }
        task: apply-node
        vars:
          IP: '{{.ITEM}}'
          MODE: '{{.MODE}}'
    vars:
      MODE: '{{.MODE | default "auto"}}'
      IP_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    preconditions:
      - which jq talosctl

  upgrade-cluster:
    desc: Upgrade Talos across the whole cluster
    cmds:
      - for: { var: IP_ADDRS }
        task: upgrade-node
        vars:
          IP: '{{.ITEM}}'
    vars:
      IP_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    preconditions:
      - which jq talosctl

  reboot-cluster:
    desc: Reboot Talos across the whole cluster [MODE=default]
    cmds:
      - for: { var: IP_ADDRS }
        task: reboot-node
        vars:
          IP: '{{.ITEM}}'
          MODE: '{{.MODE}}'
    vars:
      IP_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    preconditions:
      - which jq talosctl

  down:
    internal: true
    cmds:
      - until (kubectl wait cephcluster --for=jsonpath=.status.ceph.health=HEALTH_OK --timeout=10m --all --all-namespaces &>/dev/null || true); do sleep 5; done
      - until (kubectl wait jobs --all --all-namespaces --for=condition=complete --timeout=5m &>/dev/null || true); do sleep 5; done
    preconditions:
      - which kubectl

  up:
    internal: true
    cmds:
      - until (kubectl wait cephcluster --for=jsonpath=.status.ceph.health=HEALTH_OK --timeout=10m --all --all-namespaces &>/dev/null || true); do sleep 5; done
      - until (kubectl wait jobs --all --all-namespaces --for=condition=complete --timeout=5m &>/dev/null || true); do sleep 5; done
    preconditions:
      - which kubectl
