---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: kube-apiserver-pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: "10.0.4.26/32"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.name": "kube-apiserver"
      "io.kubernetes.service.namespace": "kube-system"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: kube-system
  annotations:
    io.cilium/lb-ipam-ips: "10.0.4.26"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
