---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
  - ../../components/common-user
resources:
  - ./blackbox-exporter/ks.yaml
  - ./gatus/ks.yaml
  - ./keda/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./snmp-exporter/ks.yaml
