---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
  - ../../components/common-user
resources:
  - ./jellyfin/ks.yaml
  - ./plex/ks.yaml
