---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/common
  - ../../components/common-user
resources:
  - ./flaresolverr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./slskd/ks.yaml
