---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rss-forwarder
spec:
  dataFrom:
    - extract:
        key: discord
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1h
  target:
    deletionPolicy: Delete
    name: rss-forwarder-secret
    template:
      data:
        config.toml: |-
          [feeds.gh_onedr0p_cluster-template]
          url = "https://github.com/onedr0p/cluster-template/commits/main/.atom"
          interval = "10m"
          retry_limit = 5
          sink.type = "discord"
          sink.url = "{{ .ONEDR0P_TEMPLATE_DISCORD_WEBHOOK }}"
          [feeds.gh_homeops_containers]
          url = "https://github.com/home-operations/containers/commits/main/.atom"
          interval = "10m"
          retry_limit = 5
          sink.type = "discord"
          sink.url = "{{ .HOMEOPS_CONTAINERS_DISCORD_WEBHOOK }}"
          [feeds.gh_homeops_charts-mirror]
          url = "https://github.com/home-operations/charts-mirror/commits/main/.atom"
          interval = "10m"
          retry_limit = 5
          sink.type = "discord"
          sink.url = "{{ .HOMEOPS_CHARTS_MIRROR_DISCORD_WEBHOOK }}"
      engineVersion: v2
