---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rss-forwarder
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rss-forwarder
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      rss-forwarder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/morphy2k/rss-forwarder
              tag: 0.7.1@sha256:5899e8f6fa88dbc8db3396ba9a81b218834d4be2437c010504d3c57b13529f48
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &disabled
                enabled: false
              readiness: *disabled
              startup: *disabled
            resources:
              limits:
                memory: 64M
              requests:
                cpu: 5m
                memory: 10M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    persistence:
      config:
        enabled: true
        type: secret
        name: "{{ .Release.Name }}-secret"
        globalMounts:
          - path: /data/config.toml
            subPath: config.toml
            readOnly: true
