# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-ids-secret
stringData:
  BW_ORGANIZATION_ID: ENC[AES256_GCM,data:N646GUtYayXOXR8VH5kTvWGjIoSjMWtjcX8QNnr5CCxdrcAt,iv:X+hsLFVFyV6wPG8j39pQSjJ6d+0iEqGEJUHmDzPTvbs=,tag:iZ3vxIWQaFX0s3GXryn68g==,type:str]
  BW_PROJECT_ID: ENC[AES256_GCM,data:wRZ+Z2Pa9IHemQnoUYXAGkD8848BGA0NZD4QDLQr4cw7wI1e,iv:edgrMvAaw3o7JCehr+81A1KO1BxaAj80IL80XUMrfSs=,tag:cEZv0/ZnIR8KGln6ogBcdQ==,type:str]
sops:
  age:
    - recipient: age19838570kqjm060wxe9lc9pclvum5tzepsgnc6r6h8l8sccartexq7g05rn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUDBrZU9pMno2UzJOWE1Z
        ay8yTnFBbmkxeUtEcHN2MjVQNVNIQUVBSlNBClRyaEloRzgvSDVLOGFLMlZ6YmMv
        dW1zUThZL2pYSkUzbEFRK0xOejUwb2MKLS0tIDdNdnFRcEt6aUJYSW8rUjd1bzhy
        NEt6SHZZeENnU3JjQzI2SzZlTmQybW8Kk13yuSdDytmUH1Vbmiupl3lWE/7vbipr
        00s/4IfgEK4Yxv4qO8pN4XDbHD5/v1/5L7ZD1ZW6h+M8FVQkDuAgIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T18:18:24Z"
  mac: ENC[AES256_GCM,data:nsDsr9334jDusZ23MVxYa/O5VI7+rMTHleFdkZMlvvIJx/a9E/eV5ckf9VWltpiqQEp2QMTALbR+G983VEVJOVpqXuyVcGqHRzoVkTSa0fMON88TGMPNNqka2p34eggRCW1m36T4FeD0Fm7UfjfPncRpg0D7dfBRMr4MW2ZGJ5Q=,iv:H2QhIPIVuPdgQWacL+hcgbuehQTpttVY+3WgcCom9nU=,tag:nJm6it8gMg6sdR9nxz5hWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
