---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitwarden-ids-secret.sops.yaml
  - ./helmrelease.yaml
  - ./network-policy.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: external-secrets-values
    files:
      - values.yaml=./helm/values.yaml
configurations:
  - ./helm/kustomizeconfig.yaml
