---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: qbtools
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: downloads
  values:
    controllers:
      tagging:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        initContainers:
          tag: &container
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.21.2@sha256:33da584c9d71bb2d8b9931995c41599bef1fdebf52cf5408cdd09175069f299a
            env:
              SABNZBD_HOST: sabnzbd.downloads.svc.cluster.local
              SABNZBD_PORT: 8080
              QBITTORRENT_HOST: qbittorrent.downloads.svc.cluster.local
              QBITTORRENT_PORT: 8080
              QBITTORRENT_USER: ${QBITTORRENT_USERNAME}
              QBITTORRENT_PASS: ${QBITTORRENT_PASSWORD}
            envFrom:
              - secretRef:
                  name: qbtools-secret
            args: [
              "tagging",
              "--added-on",
              "--expired",
              "--last-activity",
              "--sites",
              "--unregistered",
              "--not-linked",
              "-U", "$(QBITTORRENT_USERNAME)",
              "-P", "$(QBITTORRENT_PASSWORD)"
            ]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 256M
        containers:
          unregistered:
            <<: *container
            args: [
              "prune",
              "--exclude-category", "manual",
              "--exclude-category", "music",
              "--exclude-tag", "added:1d",
              "--include-tag", "unregistered",
              "--with-data",
              # "--dry-run"
              "-U", "$(QBITTORRENT_USERNAME)",
              "-P", "$(QBITTORRENT_PASSWORD)"
            ]
          expired:
            <<: *container
            args: [
              "prune",
              "--exclude-category", "manual",
              "--exclude-category", "music",
              "--exclude-tag", "added:1d",
              "--include-tag", "expired",
              "--with-data",
              # "--dry-run"
              "-U", "$(QBITTORRENT_USERNAME)",
              "-P", "$(QBITTORRENT_PASSWORD)"
            ]
        pod:
          restartPolicy: Never
      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: 0 0 * * 0
          suspend: true
        containers:
          app:
            <<: *container
            args: [
              "orphaned",
              "--exclude-pattern", "*_unpackerred*",
              # "--dry-run"
              "-U", "$(QBITTORRENT_USERNAME)",
              "-P", "$(QBITTORRENT_PASSWORD)"
            ]
        pod:
          restartPolicy: Never
      reannounce:
        containers:
          app:
            <<: *container
            args: [
              "reannounce",
              "--process-seeding",
              "-U", "$(QBITTORRENT_USERNAME)",
              "-P", "$(QBITTORRENT_PASSWORD)"
            ]
      #limiter:
      #  containers:
      #    app:
      #      <<: *container
      #      args: [
      #        "limiter",
      #        "--max-line-speed-mbps", "40",
      #        "--max-percent", "0.9",
      #        "--limit-percent", "0.45",
      #        "--interval", "5"
      #        "-U", "$(QBITTORRENT_USERNAME)",
      #        "-P", "$(QBITTORRENT_PASSWORD)"
      #      ]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    persistence:
      secret-file:
        type: secret
        name: qbtools-config-secret
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      media:
        type: nfs
        server: norco.${LOCAL_DOMAIN}
        path: /mnt/space/media
        globalMounts:
          - path: /mnt/downloads/torrents
            subPath: downloads/torrents
